markdown: maruku
pygments: true

permalink: /:title/
exclude: []

title: 'i talk too much'
email: 'sethetter@gmail.com'
twitter_url: 'http://twitter.com/sethetter'
feedburner_url: 'http://feeds.feedburner.com/italktoomuch'

tagline: "Ramblings on code, tech, design, music, and some other stuff. By Seth Etter."
